<%@ Page Language="VB" AutoEventWireup="false" MasterPageFile="~/controls/AdminMaster.master" Title="Supply Phase" CodeFile="default.aspx.vb" Inherits="Index"  %>

<asp:content ContentPlaceHolderId="ph" ID="Content" runat="server">

<input type="hidden" name="ACTION" />
<h4>Supply Phase Administration</h4>
<p>
    <b>Add/Rename/Delete Supply Phases</b>
    <br/>
    <font class="desc">* Departments with number in parentheses next to the name cannot be deleted, because contain products. </font></p>

    <table width="100%" border="0">
        <tr>
            <td valign="top" width="50%">
                <CC:CustomTreeView id="rtvMain" runat="server" EnableViewState="false" AutoGenerateDataBindings="false" PopuplateNodesFromClient="true" Type="Radio"></CC:CustomTreeView>
            </td>
            <td valign="top" width="50%">
                <table border="0" cellpadding="2" cellspacing="0" class="view" width="280">
                    <tr>
                        <td class="row" colspan="2"><b>Add New Supply Phase</b>&nbsp;<br>
                            <font class="desc">(Please select the parent department on the left)</font></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><b class="smaller">Name:</b></td>
                        <td><asp:TextBox Text="" id="txtNewPhase" Runat="server" /></td>
                        <td><asp:RequiredFieldValidator ID="rfvNewPhase" runat="server" Display="Dynamic" ControlToValidate="txtNewPhase" ErrorMessage="'Name' is blank" ValidationGroup="AddPhase"></asp:RequiredFieldValidator></td>
                    </tr>
                    <tr>
                        <td><b class="smaller">Price Lock Days:</b></td>
                        <td><asp:TextBox ID="txtPriceLockDays" runat="server" Columns="4" MaxLength="4" style="width:75px;"></asp:TextBox></td>
                        <td>
                            <asp:RequiredFieldValidator ID="rfvPriceLockDays" runat="server" ControlToValidate="txtPriceLockDays" Display="Dynamic" ErrorMessage="'Price Lock Days' is blank" ValidationGroup="AddPhase"></asp:RequiredFieldValidator>
                            <CC:IntegerValidator ID="ivPriceLockDays" runat="server" ControlToValidate="txtPriceLockDays" Display="Dynamic" ErrorMessage="'Price Lock Days' is invalid" ValidationGroup="AddPhase"></CC:IntegerValidator>
                        </td>
                    </tr>
                    <tr>
                        <td><b class="smaller">Excluded LLCs:</b></td>
                        <td>
                            <CC:ListBox ID="lbExclude" runat="server" Rows="8"></CC:ListBox>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><CC:OneClickButton runat="server" ID="btnAdd" Text="Add Phase" cssclass="btn" ValidationGroup="AddPhase"/></td>
                        <td></td>
                    </tr>
                </table>
                <p>
                    <table border="0" cellpadding="2" cellspacing="0" class="view" width="280">
                        <tr class="row">
                            <td colspan="2"><b>Rename Supply Phase</b>&nbsp;<br>
                                <font class="desc">(Please select the department on the left)</font></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>Supply Phase:<br>
                                <asp:TextBox Text="" id="txtRename" columns="20" maxlength="50" Runat="server" />
                                &nbsp;
                                <CC:OneClickButton id="btnRename" cssclass="btn" Text="Rename" Runat="server" CausesValidation="false" />
                            </td>
                        </tr>
                    </table>
                </p><p>
                    <table border="0" cellpadding="2" cellspacing="0" class="view" width="280">
                        <tr class="row">
                            <td colspan="2"><b>Delete Supply Phase</b>&nbsp;<br>
                                <font class="desc">(Please select the department on the left)</font></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>Delete selected supply phase&nbsp;
                                <CC:OneClickButton id="btnDelete" cssclass="btn" Text="Delete" Runat="server" CuasesValidation="false" />
                            </td>
                        </tr>
                    </table>
                </p>
            </td>
        </tr>
    </table>

    <p/>
    <hr size=1 color=black>
    <p/>
    <b>Move Supply Phases</b>
    <br>
    <font class="desc">Please select source and destination supply phase and then click 
        the </font>&nbsp;<CC:OneClickButton ID="btnMove" cssclass="btn" value="Move" Runat="server" Text="Move" />
    <font class="desc">button</font>
<p>
    <table width="100%" border="0">
        <tr>
            <td valign="top" width="50%">
                <b>Source Supply Phase</b><br>
                <CC:CustomTreeView ID="rtvSource" runat="server" EnableViewState="false" AutoGenerateDataBindings="false" PopulateNodesFromClient="true" Type="Radio"></CC:CustomTreeView>
            </td>
            <td valign="top" width="50%">
                <b>Destination Supply Phase</b><br>
                <CC:CustomTreeView ID="rtvDestination" runat="server" EnableViewState="false" AutoGenerateDataBindings="false" PopulateNodesFromClient="true" Type="Radio"></CC:CustomTreeView>
            </td>
        </tr>
    </table>
    <br />
    &nbsp; </TD></TR></TABLE></p>
</asp:content>