<%@ Control Language="VB" AutoEventWireup="false" CodeFile="StoreDepartmentTree.ascx.vb" Inherits="StoreDepartmentTree" %>
<asp:TreeView id="Tree" runat="server" EnableViewState="True" ShowCheckBoxes="All" CollapseImageToolTip="Collapse this Department" 
    ExpandImageToolTip="Expand this Department" AutoGenerateDataBindings="false">
    <SelectedNodeStyle Font-Names="Arial,Lucinda,Verdana,Helvetica" Font-Size="12px" ForeColor="white" />
    <HoverNodeStyle Font-Names="Arial,Lucinda,Verdana,Helvetica" Font-Size="12px" ForeColor="black" />
    <NodeStyle CssClass="NodeStyle" HorizontalPadding="0" />
</asp:TreeView>
