'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Vindicia.Transaction
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://soap.vindicia.com/Transaction", ConfigurationName:="Vindicia.Transaction.TransactionPortType")>  _
    Public Interface TransactionPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#fetchByVid", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function fetchByVid(<System.Runtime.InteropServices.OutAttribute()> ByRef transaction As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal vid As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#fetchByAccount", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function fetchByAccount(<System.Runtime.InteropServices.OutAttribute()> ByRef transactions() As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal account As Vindicia.AllDataTypes.Account) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#fetchByMerchantTransactionId", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function fetchByMerchantTransactionId(<System.Runtime.InteropServices.OutAttribute()> ByRef transaction As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantTransactionId As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#fetchDeltaSince", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function fetchDeltaSince(<System.Runtime.InteropServices.OutAttribute()> ByRef transactions() As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal timestamp As Date, ByVal page As Integer, ByVal pageSize As Integer, ByVal paymentMethod As Vindicia.AllDataTypes.PaymentMethod) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#fetchDelta", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function fetchDelta(<System.Runtime.InteropServices.OutAttribute()> ByRef transactions() As Vindicia.AllDataTypes.Transaction, <System.Runtime.InteropServices.OutAttribute()> ByRef startDate As Date, <System.Runtime.InteropServices.OutAttribute()> ByRef endDate As Date, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal pageSize As Integer) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#fetchByAutobill", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function fetchByAutobill(<System.Runtime.InteropServices.OutAttribute()> ByRef transactions() As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal autobill As Vindicia.AllDataTypes.AutoBill) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#fetchSearchPage", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function fetchSearchPage(<System.Runtime.InteropServices.OutAttribute()> ByRef transactions() As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal VID As String, ByRef objectsPerPage As Integer, ByRef pageNumber As Integer, ByVal nameValues() As Vindicia.AllDataTypes.NameValuePair) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#auth", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function auth(<System.ServiceModel.MessageParameterAttribute(Name:="auth")> ByVal auth1 As Vindicia.AllDataTypes.Authentication, ByRef transaction As Vindicia.AllDataTypes.Transaction, ByVal explicitCapture As Boolean, ByVal minChargebackProbability As Integer) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#calculateSalesTax", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function calculateSalesTax(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef transaction As Vindicia.AllDataTypes.Transaction, <System.Runtime.InteropServices.OutAttribute()> ByRef addressType As Vindicia.AllDataTypes.AddressType, <System.Runtime.InteropServices.OutAttribute()> ByRef originalAddress As Vindicia.AllDataTypes.Address, <System.Runtime.InteropServices.OutAttribute()> ByRef correctedAddress As Vindicia.AllDataTypes.Address, <System.Runtime.InteropServices.OutAttribute()> ByRef taxItems() As Vindicia.AllDataTypes.SalesTax, <System.Runtime.InteropServices.OutAttribute()> ByRef totalTax As Decimal) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#capture", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function capture(<System.Runtime.InteropServices.OutAttribute()> ByRef qtySuccess As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef qtyFail As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef results() As Vindicia.AllDataTypes.CaptureResult, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal transactions() As Vindicia.AllDataTypes.Transaction) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#cancel", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function cancel(<System.Runtime.InteropServices.OutAttribute()> ByRef qtySuccess As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef qtyFail As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef results() As Vindicia.AllDataTypes.CancelResult, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal transactions() As Vindicia.AllDataTypes.Transaction) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#authCapture", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function authCapture(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef transaction As Vindicia.AllDataTypes.Transaction) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#report", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function report(ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal transactions() As Vindicia.AllDataTypes.Transaction) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Transaction#score", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreCode)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.ScoreControl)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CancelResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.CaptureResult)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.SalesTax)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TransactionItem)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair))> _
        Function score(<System.ServiceModel.MessageParameterAttribute(Name:="score"), System.Runtime.InteropServices.OutAttribute()> ByRef score1 As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef scoreCodes() As Vindicia.AllDataTypes.ScoreCode, <System.Runtime.InteropServices.OutAttribute()> ByRef improveScore As String, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal transaction As Vindicia.AllDataTypes.Transaction, ByVal formData As String, ByVal scoreControl() As Vindicia.AllDataTypes.ScoreControl) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Public Interface TransactionPortTypeChannel
        Inherits Vindicia.Transaction.TransactionPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class TransactionPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of Vindicia.Transaction.TransactionPortType)
        Implements Vindicia.Transaction.TransactionPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function fetchByVid(<System.Runtime.InteropServices.OutAttribute()> ByRef transaction As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal vid As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.fetchByVid
            Return MyBase.Channel.fetchByVid(transaction, auth, vid)
        End Function
        
        Public Function fetchByAccount(<System.Runtime.InteropServices.OutAttribute()> ByRef transactions() As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal account As Vindicia.AllDataTypes.Account) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.fetchByAccount
            Return MyBase.Channel.fetchByAccount(transactions, auth, account)
        End Function
        
        Public Function fetchByMerchantTransactionId(<System.Runtime.InteropServices.OutAttribute()> ByRef transaction As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantTransactionId As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.fetchByMerchantTransactionId
            Return MyBase.Channel.fetchByMerchantTransactionId(transaction, auth, merchantTransactionId)
        End Function
        
        Public Function fetchDeltaSince(<System.Runtime.InteropServices.OutAttribute()> ByRef transactions() As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal timestamp As Date, ByVal page As Integer, ByVal pageSize As Integer, ByVal paymentMethod As Vindicia.AllDataTypes.PaymentMethod) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.fetchDeltaSince
            Return MyBase.Channel.fetchDeltaSince(transactions, auth, timestamp, page, pageSize, paymentMethod)
        End Function
        
        Public Function fetchDelta(<System.Runtime.InteropServices.OutAttribute()> ByRef transactions() As Vindicia.AllDataTypes.Transaction, <System.Runtime.InteropServices.OutAttribute()> ByRef startDate As Date, <System.Runtime.InteropServices.OutAttribute()> ByRef endDate As Date, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal pageSize As Integer) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.fetchDelta
            Return MyBase.Channel.fetchDelta(transactions, startDate, endDate, auth, pageSize)
        End Function
        
        Public Function fetchByAutobill(<System.Runtime.InteropServices.OutAttribute()> ByRef transactions() As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal autobill As Vindicia.AllDataTypes.AutoBill) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.fetchByAutobill
            Return MyBase.Channel.fetchByAutobill(transactions, auth, autobill)
        End Function
        
        Public Function fetchSearchPage(<System.Runtime.InteropServices.OutAttribute()> ByRef transactions() As Vindicia.AllDataTypes.Transaction, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal VID As String, ByRef objectsPerPage As Integer, ByRef pageNumber As Integer, ByVal nameValues() As Vindicia.AllDataTypes.NameValuePair) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.fetchSearchPage
            Return MyBase.Channel.fetchSearchPage(transactions, auth, VID, objectsPerPage, pageNumber, nameValues)
        End Function
        
        Public Function auth(ByVal auth1 As Vindicia.AllDataTypes.Authentication, ByRef transaction As Vindicia.AllDataTypes.Transaction, ByVal explicitCapture As Boolean, ByVal minChargebackProbability As Integer) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.auth
            Return MyBase.Channel.auth(auth1, transaction, explicitCapture, minChargebackProbability)
        End Function
        
        Public Function calculateSalesTax(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef transaction As Vindicia.AllDataTypes.Transaction, <System.Runtime.InteropServices.OutAttribute()> ByRef addressType As Vindicia.AllDataTypes.AddressType, <System.Runtime.InteropServices.OutAttribute()> ByRef originalAddress As Vindicia.AllDataTypes.Address, <System.Runtime.InteropServices.OutAttribute()> ByRef correctedAddress As Vindicia.AllDataTypes.Address, <System.Runtime.InteropServices.OutAttribute()> ByRef taxItems() As Vindicia.AllDataTypes.SalesTax, <System.Runtime.InteropServices.OutAttribute()> ByRef totalTax As Decimal) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.calculateSalesTax
            Return MyBase.Channel.calculateSalesTax(auth, transaction, addressType, originalAddress, correctedAddress, taxItems, totalTax)
        End Function
        
        Public Function capture(<System.Runtime.InteropServices.OutAttribute()> ByRef qtySuccess As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef qtyFail As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef results() As Vindicia.AllDataTypes.CaptureResult, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal transactions() As Vindicia.AllDataTypes.Transaction) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.capture
            Return MyBase.Channel.capture(qtySuccess, qtyFail, results, auth, transactions)
        End Function
        
        Public Function cancel(<System.Runtime.InteropServices.OutAttribute()> ByRef qtySuccess As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef qtyFail As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef results() As Vindicia.AllDataTypes.CancelResult, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal transactions() As Vindicia.AllDataTypes.Transaction) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.cancel
            Return MyBase.Channel.cancel(qtySuccess, qtyFail, results, auth, transactions)
        End Function
        
        Public Function authCapture(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef transaction As Vindicia.AllDataTypes.Transaction) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.authCapture
            Return MyBase.Channel.authCapture(auth, transaction)
        End Function
        
        Public Function report(ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal transactions() As Vindicia.AllDataTypes.Transaction) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.report
            Return MyBase.Channel.report(auth, transactions)
        End Function
        
        Public Function score(<System.Runtime.InteropServices.OutAttribute()> ByRef score1 As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef scoreCodes() As Vindicia.AllDataTypes.ScoreCode, <System.Runtime.InteropServices.OutAttribute()> ByRef improveScore As String, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal transaction As Vindicia.AllDataTypes.Transaction, ByVal formData As String, ByVal scoreControl() As Vindicia.AllDataTypes.ScoreControl) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Transaction.TransactionPortType.score
            Return MyBase.Channel.score(score1, scoreCodes, improveScore, auth, transaction, formData, scoreControl)
        End Function
    End Class
End Namespace
