'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Vindicia.BillingPlan
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://soap.vindicia.com/BillingPlan", ConfigurationName:="Vindicia.BillingPlan.BillingPlanPortType")>  _
    Public Interface BillingPlanPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/BillingPlan#update", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function update(ByVal auth As AllDataTypes.Authentication, ByRef billingPlan As AllDataTypes.BillingPlan, <System.Runtime.InteropServices.OutAttribute()> ByRef created As Boolean) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/BillingPlan#fetchByVid", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function fetchByVid(<System.Runtime.InteropServices.OutAttribute()> ByRef billingPlan As AllDataTypes.BillingPlan, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal vid As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/BillingPlan#fetchByMerchantBillingPlanId", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function fetchByMerchantBillingPlanId(<System.Runtime.InteropServices.OutAttribute()> ByRef billingPlan As Vindicia.AllDataTypes.BillingPlan, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantBillingPlanId As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/BillingPlan#fetchByBillingPlanStatus", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function fetchByBillingPlanStatus(<System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As AllDataTypes.BillingPlan, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal status As Vindicia.AllDataTypes.BillingPlanStatus) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/BillingPlan#fetchAll", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function fetchAll(<System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As AllDataTypes.BillingPlan, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal page As Integer, ByVal pageSize As Integer) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/BillingPlan#fetchByMerchantEntitlementId", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function fetchByMerchantEntitlementId(<System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As AllDataTypes.BillingPlan, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantEntitlementId As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Public Interface BillingPlanPortTypeChannel
        Inherits Vindicia.BillingPlan.BillingPlanPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class BillingPlanPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of Vindicia.BillingPlan.BillingPlanPortType)
        Implements Vindicia.BillingPlan.BillingPlanPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function update(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef billingPlan As Vindicia.AllDataTypes.BillingPlan, <System.Runtime.InteropServices.OutAttribute()> ByRef created As Boolean) As Vindicia.AllDataTypes.[Return] Implements Vindicia.BillingPlan.BillingPlanPortType.update
            Return MyBase.Channel.update(auth, billingPlan, created)
        End Function
        
        Public Function fetchByVid(<System.Runtime.InteropServices.OutAttribute()> ByRef billingPlan As Vindicia.AllDataTypes.BillingPlan, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal vid As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.BillingPlan.BillingPlanPortType.fetchByVid
            Return MyBase.Channel.fetchByVid(billingPlan, auth, vid)
        End Function
        
        Public Function fetchByMerchantBillingPlanId(<System.Runtime.InteropServices.OutAttribute()> ByRef billingPlan As Vindicia.AllDataTypes.BillingPlan, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantBillingPlanId As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.BillingPlan.BillingPlanPortType.fetchByMerchantBillingPlanId
            Return MyBase.Channel.fetchByMerchantBillingPlanId(billingPlan, auth, merchantBillingPlanId)
        End Function
        
        Public Function fetchByBillingPlanStatus(<System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As AllDataTypes.BillingPlan, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal status As Vindicia.AllDataTypes.BillingPlanStatus) As Vindicia.AllDataTypes.[Return] Implements Vindicia.BillingPlan.BillingPlanPortType.fetchByBillingPlanStatus
            Return MyBase.Channel.fetchByBillingPlanStatus(billingPlans, auth, status)
        End Function
        
        Public Function fetchAll(<System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As AllDataTypes.BillingPlan, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal page As Integer, ByVal pageSize As Integer) As Vindicia.AllDataTypes.[Return] Implements Vindicia.BillingPlan.BillingPlanPortType.fetchAll
            Return MyBase.Channel.fetchAll(billingPlans, auth, page, pageSize)
        End Function
        
        Public Function fetchByMerchantEntitlementId(<System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As AllDataTypes.BillingPlan, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantEntitlementId As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.BillingPlan.BillingPlanPortType.fetchByMerchantEntitlementId
            Return MyBase.Channel.fetchByMerchantEntitlementId(billingPlans, auth, merchantEntitlementId)
        End Function
    End Class
End Namespace
