'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Vindicia_OLD.BillingPlan
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", ConfigurationName:="Vindicia_OLD.BillingPlan.BillingPlanPortType")>  _
    Public Interface BillingPlanPortType
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/v7_0/BillingPlan#update", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function update(ByVal request As Vindicia_OLD.BillingPlan.updateRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia_OLD.BillingPlan.updateResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/v7_0/BillingPlan#fetchByVid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function fetchByVid(ByVal request As Vindicia_OLD.BillingPlan.fetchByVidRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia_OLD.BillingPlan.fetchByVidResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/v7_0/BillingPlan#fetchByMerchantBillingPlanId", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function fetchByMerchantBillingPlanId(ByVal request As Vindicia_OLD.BillingPlan.fetchByMerchantBillingPlanIdRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia_OLD.BillingPlan.fetchByMerchantBillingPlanIdResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/v7_0/BillingPlan#fetchByBillingPlanStatus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function fetchByBillingPlanStatus(ByVal request As Vindicia_OLD.BillingPlan.fetchByBillingPlanStatusRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia_OLD.BillingPlan.fetchByBillingPlanStatusResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/v7_0/BillingPlan#fetchAll", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function fetchAll(ByVal request As Vindicia_OLD.BillingPlan.fetchAllRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia_OLD.BillingPlan.fetchAllResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/v7_0/BillingPlan#fetchByMerchantEntitlementId", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function fetchByMerchantEntitlementId(ByVal request As Vindicia_OLD.BillingPlan.fetchByMerchantEntitlementIdRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia_OLD.BillingPlan.fetchByMerchantEntitlementIdResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/v7_0/BillingPlan#fetchAllInSeason", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function fetchAllInSeason(ByVal request As Vindicia_OLD.BillingPlan.fetchAllInSeasonRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia_OLD.BillingPlan.fetchAllInSeasonResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/v7_0/BillingPlan#fetchAllOffSeason", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function fetchAllOffSeason(ByVal request As Vindicia_OLD.BillingPlan.fetchAllOffSeasonRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia_OLD.BillingPlan.fetchAllOffSeasonResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class Authentication
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private versionField As String
        
        Private loginField As String
        
        Private passwordField As String
        
        Private evidField As String
        
        Private userAgentField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
                Me.RaisePropertyChanged("version")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property login() As String
            Get
                Return Me.loginField
            End Get
            Set
                Me.loginField = value
                Me.RaisePropertyChanged("login")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property evid() As String
            Get
                Return Me.evidField
            End Get
            Set
                Me.evidField = value
                Me.RaisePropertyChanged("evid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property userAgent() As String
            Get
                Return Me.userAgentField
            End Get
            Set
                Me.userAgentField = value
                Me.RaisePropertyChanged("userAgent")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class [Return]
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private returnCodeField As Integer
        
        Private returnStringField As String
        
        Private soapIdField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property returnCode() As Integer
            Get
                Return Me.returnCodeField
            End Get
            Set
                Me.returnCodeField = value
                Me.RaisePropertyChanged("returnCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property returnString() As String
            Get
                Return Me.returnStringField
            End Get
            Set
                Me.returnStringField = value
                Me.RaisePropertyChanged("returnString")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property soapId() As String
            Get
                Return Me.soapIdField
            End Get
            Set
                Me.soapIdField = value
                Me.RaisePropertyChanged("soapId")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class Season
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private descriptionField As String
        
        Private startDateField As Date
        
        Private startDateFieldSpecified As Boolean
        
        Private endDateField As Date
        
        Private endDateFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date", Order:=1)>  _
        Public Property startDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
                Me.RaisePropertyChanged("startDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property startDateSpecified() As Boolean
            Get
                Return Me.startDateFieldSpecified
            End Get
            Set
                Me.startDateFieldSpecified = value
                Me.RaisePropertyChanged("startDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date", Order:=2)>  _
        Public Property endDate() As Date
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
                Me.RaisePropertyChanged("endDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property endDateSpecified() As Boolean
            Get
                Return Me.endDateFieldSpecified
            End Get
            Set
                Me.endDateFieldSpecified = value
                Me.RaisePropertyChanged("endDateSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class SeasonSet
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private vIDField As String
        
        Private merchantSeasonSetIdField As String
        
        Private seasonsField() As Season
        
        Private nameValuesField() As NameValuePair
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property VID() As String
            Get
                Return Me.vIDField
            End Get
            Set
                Me.vIDField = value
                Me.RaisePropertyChanged("VID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property merchantSeasonSetId() As String
            Get
                Return Me.merchantSeasonSetIdField
            End Get
            Set
                Me.merchantSeasonSetIdField = value
                Me.RaisePropertyChanged("merchantSeasonSetId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("seasons", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property seasons() As Season()
            Get
                Return Me.seasonsField
            End Get
            Set
                Me.seasonsField = value
                Me.RaisePropertyChanged("seasons")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("nameValues", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property nameValues() As NameValuePair()
            Get
                Return Me.nameValuesField
            End Get
            Set
                Me.nameValuesField = value
                Me.RaisePropertyChanged("nameValues")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class NameValuePair
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nameField As String
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class MerchantEntitlementId
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("description")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class Token
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private vIDField As String
        
        Private merchantTokenIdField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property VID() As String
            Get
                Return Me.vIDField
            End Get
            Set
                Me.vIDField = value
                Me.RaisePropertyChanged("VID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property merchantTokenId() As String
            Get
                Return Me.merchantTokenIdField
            End Get
            Set
                Me.merchantTokenIdField = value
                Me.RaisePropertyChanged("merchantTokenId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("description")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class TokenAmount
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private tokenField As Token
        
        Private amountField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property token() As Token
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
                Me.RaisePropertyChanged("token")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property amount() As Integer
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("amount")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class BillingPlanPrice
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private amountField As Decimal
        
        Private amountFieldSpecified As Boolean
        
        Private currencyField As String
        
        Private priceListNameField As String
        
        Private tokenAmountField As TokenAmount
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("amount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property amountSpecified() As Boolean
            Get
                Return Me.amountFieldSpecified
            End Get
            Set
                Me.amountFieldSpecified = value
                Me.RaisePropertyChanged("amountSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property currency() As String
            Get
                Return Me.currencyField
            End Get
            Set
                Me.currencyField = value
                Me.RaisePropertyChanged("currency")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property priceListName() As String
            Get
                Return Me.priceListNameField
            End Get
            Set
                Me.priceListNameField = value
                Me.RaisePropertyChanged("priceListName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property tokenAmount() As TokenAmount
            Get
                Return Me.tokenAmountField
            End Get
            Set
                Me.tokenAmountField = value
                Me.RaisePropertyChanged("tokenAmount")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class BillingPlanPeriod
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private typeField As BillingPeriodType
        
        Private typeFieldSpecified As Boolean
        
        Private quantityField As Integer
        
        Private quantityFieldSpecified As Boolean
        
        Private cyclesField As Integer
        
        Private cyclesFieldSpecified As Boolean
        
        Private pricesField() As BillingPlanPrice
        
        Private expireWarningDaysField As Integer
        
        Private expireWarningDaysFieldSpecified As Boolean
        
        Private doNotNotifyFirstBillField As Boolean
        
        Private doNotNotifyFirstBillFieldSpecified As Boolean
        
        Private freeField As Boolean
        
        Private freeFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property type() As BillingPeriodType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
                Me.RaisePropertyChanged("type")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property typeSpecified() As Boolean
            Get
                Return Me.typeFieldSpecified
            End Get
            Set
                Me.typeFieldSpecified = value
                Me.RaisePropertyChanged("typeSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property quantity() As Integer
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
                Me.RaisePropertyChanged("quantity")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property quantitySpecified() As Boolean
            Get
                Return Me.quantityFieldSpecified
            End Get
            Set
                Me.quantityFieldSpecified = value
                Me.RaisePropertyChanged("quantitySpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property cycles() As Integer
            Get
                Return Me.cyclesField
            End Get
            Set
                Me.cyclesField = value
                Me.RaisePropertyChanged("cycles")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cyclesSpecified() As Boolean
            Get
                Return Me.cyclesFieldSpecified
            End Get
            Set
                Me.cyclesFieldSpecified = value
                Me.RaisePropertyChanged("cyclesSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("prices", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property prices() As BillingPlanPrice()
            Get
                Return Me.pricesField
            End Get
            Set
                Me.pricesField = value
                Me.RaisePropertyChanged("prices")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property expireWarningDays() As Integer
            Get
                Return Me.expireWarningDaysField
            End Get
            Set
                Me.expireWarningDaysField = value
                Me.RaisePropertyChanged("expireWarningDays")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property expireWarningDaysSpecified() As Boolean
            Get
                Return Me.expireWarningDaysFieldSpecified
            End Get
            Set
                Me.expireWarningDaysFieldSpecified = value
                Me.RaisePropertyChanged("expireWarningDaysSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property doNotNotifyFirstBill() As Boolean
            Get
                Return Me.doNotNotifyFirstBillField
            End Get
            Set
                Me.doNotNotifyFirstBillField = value
                Me.RaisePropertyChanged("doNotNotifyFirstBill")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property doNotNotifyFirstBillSpecified() As Boolean
            Get
                Return Me.doNotNotifyFirstBillFieldSpecified
            End Get
            Set
                Me.doNotNotifyFirstBillFieldSpecified = value
                Me.RaisePropertyChanged("doNotNotifyFirstBillSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property free() As Boolean
            Get
                Return Me.freeField
            End Get
            Set
                Me.freeField = value
                Me.RaisePropertyChanged("free")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property freeSpecified() As Boolean
            Get
                Return Me.freeFieldSpecified
            End Get
            Set
                Me.freeFieldSpecified = value
                Me.RaisePropertyChanged("freeSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Public Enum BillingPeriodType
        
        '''<remarks/>
        Day
        
        '''<remarks/>
        Week
        
        '''<remarks/>
        Month
        
        '''<remarks/>
        Year
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Partial Public Class BillingPlan
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private vIDField As String
        
        Private merchantBillingPlanIdField As String
        
        Private descriptionField As String
        
        Private statusField As BillingPlanStatus
        
        Private statusFieldSpecified As Boolean
        
        Private periodsField() As BillingPlanPeriod
        
        Private prenotifyDaysField As Integer
        
        Private prenotifyDaysFieldSpecified As Boolean
        
        Private endOfLifeTimestampField As Date
        
        Private endOfLifeTimestampFieldSpecified As Boolean
        
        Private nameValuesField() As NameValuePair
        
        Private merchantEntitlementIdsField() As MerchantEntitlementId
        
        Private billingStatementIdentifierField As String
        
        Private timesToRunField As String
        
        Private entitlementsValidForField As String
        
        Private repeatEveryField As String
        
        Private seasonSetField As SeasonSet
        
        Private daysBeforeSeasonToBillField As Integer
        
        Private daysBeforeSeasonToBillFieldSpecified As Boolean
        
        Private daysEntitledBeforeSeasonField As Integer
        
        Private daysEntitledBeforeSeasonFieldSpecified As Boolean
        
        Private daysEntitledAfterSeasonField As Integer
        
        Private daysEntitledAfterSeasonFieldSpecified As Boolean
        
        Private entitledOffSeasonField As Boolean
        
        Private entitledOffSeasonFieldSpecified As Boolean
        
        Private skipInitialFreeWhenRepeatingField As Boolean
        
        Private skipInitialFreeWhenRepeatingFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property VID() As String
            Get
                Return Me.vIDField
            End Get
            Set
                Me.vIDField = value
                Me.RaisePropertyChanged("VID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property merchantBillingPlanId() As String
            Get
                Return Me.merchantBillingPlanIdField
            End Get
            Set
                Me.merchantBillingPlanIdField = value
                Me.RaisePropertyChanged("merchantBillingPlanId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property status() As BillingPlanStatus
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
                Me.RaisePropertyChanged("statusSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("periods", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property periods() As BillingPlanPeriod()
            Get
                Return Me.periodsField
            End Get
            Set
                Me.periodsField = value
                Me.RaisePropertyChanged("periods")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property prenotifyDays() As Integer
            Get
                Return Me.prenotifyDaysField
            End Get
            Set
                Me.prenotifyDaysField = value
                Me.RaisePropertyChanged("prenotifyDays")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property prenotifyDaysSpecified() As Boolean
            Get
                Return Me.prenotifyDaysFieldSpecified
            End Get
            Set
                Me.prenotifyDaysFieldSpecified = value
                Me.RaisePropertyChanged("prenotifyDaysSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property endOfLifeTimestamp() As Date
            Get
                Return Me.endOfLifeTimestampField
            End Get
            Set
                Me.endOfLifeTimestampField = value
                Me.RaisePropertyChanged("endOfLifeTimestamp")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property endOfLifeTimestampSpecified() As Boolean
            Get
                Return Me.endOfLifeTimestampFieldSpecified
            End Get
            Set
                Me.endOfLifeTimestampFieldSpecified = value
                Me.RaisePropertyChanged("endOfLifeTimestampSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("nameValues", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property nameValues() As NameValuePair()
            Get
                Return Me.nameValuesField
            End Get
            Set
                Me.nameValuesField = value
                Me.RaisePropertyChanged("nameValues")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("merchantEntitlementIds", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property merchantEntitlementIds() As MerchantEntitlementId()
            Get
                Return Me.merchantEntitlementIdsField
            End Get
            Set
                Me.merchantEntitlementIdsField = value
                Me.RaisePropertyChanged("merchantEntitlementIds")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property billingStatementIdentifier() As String
            Get
                Return Me.billingStatementIdentifierField
            End Get
            Set
                Me.billingStatementIdentifierField = value
                Me.RaisePropertyChanged("billingStatementIdentifier")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property timesToRun() As String
            Get
                Return Me.timesToRunField
            End Get
            Set
                Me.timesToRunField = value
                Me.RaisePropertyChanged("timesToRun")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property entitlementsValidFor() As String
            Get
                Return Me.entitlementsValidForField
            End Get
            Set
                Me.entitlementsValidForField = value
                Me.RaisePropertyChanged("entitlementsValidFor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property repeatEvery() As String
            Get
                Return Me.repeatEveryField
            End Get
            Set
                Me.repeatEveryField = value
                Me.RaisePropertyChanged("repeatEvery")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property seasonSet() As SeasonSet
            Get
                Return Me.seasonSetField
            End Get
            Set
                Me.seasonSetField = value
                Me.RaisePropertyChanged("seasonSet")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=14)>  _
        Public Property daysBeforeSeasonToBill() As Integer
            Get
                Return Me.daysBeforeSeasonToBillField
            End Get
            Set
                Me.daysBeforeSeasonToBillField = value
                Me.RaisePropertyChanged("daysBeforeSeasonToBill")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property daysBeforeSeasonToBillSpecified() As Boolean
            Get
                Return Me.daysBeforeSeasonToBillFieldSpecified
            End Get
            Set
                Me.daysBeforeSeasonToBillFieldSpecified = value
                Me.RaisePropertyChanged("daysBeforeSeasonToBillSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property daysEntitledBeforeSeason() As Integer
            Get
                Return Me.daysEntitledBeforeSeasonField
            End Get
            Set
                Me.daysEntitledBeforeSeasonField = value
                Me.RaisePropertyChanged("daysEntitledBeforeSeason")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property daysEntitledBeforeSeasonSpecified() As Boolean
            Get
                Return Me.daysEntitledBeforeSeasonFieldSpecified
            End Get
            Set
                Me.daysEntitledBeforeSeasonFieldSpecified = value
                Me.RaisePropertyChanged("daysEntitledBeforeSeasonSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=16)>  _
        Public Property daysEntitledAfterSeason() As Integer
            Get
                Return Me.daysEntitledAfterSeasonField
            End Get
            Set
                Me.daysEntitledAfterSeasonField = value
                Me.RaisePropertyChanged("daysEntitledAfterSeason")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property daysEntitledAfterSeasonSpecified() As Boolean
            Get
                Return Me.daysEntitledAfterSeasonFieldSpecified
            End Get
            Set
                Me.daysEntitledAfterSeasonFieldSpecified = value
                Me.RaisePropertyChanged("daysEntitledAfterSeasonSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=17)>  _
        Public Property entitledOffSeason() As Boolean
            Get
                Return Me.entitledOffSeasonField
            End Get
            Set
                Me.entitledOffSeasonField = value
                Me.RaisePropertyChanged("entitledOffSeason")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property entitledOffSeasonSpecified() As Boolean
            Get
                Return Me.entitledOffSeasonFieldSpecified
            End Get
            Set
                Me.entitledOffSeasonFieldSpecified = value
                Me.RaisePropertyChanged("entitledOffSeasonSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=18)>  _
        Public Property skipInitialFreeWhenRepeating() As Boolean
            Get
                Return Me.skipInitialFreeWhenRepeatingField
            End Get
            Set
                Me.skipInitialFreeWhenRepeatingField = value
                Me.RaisePropertyChanged("skipInitialFreeWhenRepeating")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property skipInitialFreeWhenRepeatingSpecified() As Boolean
            Get
                Return Me.skipInitialFreeWhenRepeatingFieldSpecified
            End Get
            Set
                Me.skipInitialFreeWhenRepeatingFieldSpecified = value
                Me.RaisePropertyChanged("skipInitialFreeWhenRepeatingSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.vindicia.com/v7_0/Vindicia")>  _
    Public Enum BillingPlanStatus
        
        '''<remarks/>
        Active
        
        '''<remarks/>
        Suspended
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="update", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class updateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auth As Vindicia_OLD.BillingPlan.Authentication
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billingPlan As Vindicia_OLD.BillingPlan.BillingPlan
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal billingPlan As Vindicia_OLD.BillingPlan.BillingPlan)
            MyBase.New
            Me.auth = auth
            Me.billingPlan = billingPlan
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="updateResponse", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class updateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Vindicia_OLD.BillingPlan.[Return]
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billingPlan As Vindicia_OLD.BillingPlan.BillingPlan
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public created As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Vindicia_OLD.BillingPlan.[Return], ByVal billingPlan As Vindicia_OLD.BillingPlan.BillingPlan, ByVal created As Boolean)
            MyBase.New
            Me.[return] = [return]
            Me.billingPlan = billingPlan
            Me.created = created
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchByVid", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchByVidRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auth As Vindicia_OLD.BillingPlan.Authentication
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public vid As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal vid As String)
            MyBase.New
            Me.auth = auth
            Me.vid = vid
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchByVidResponse", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchByVidResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Vindicia_OLD.BillingPlan.[Return]
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billingPlan As Vindicia_OLD.BillingPlan.BillingPlan
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Vindicia_OLD.BillingPlan.[Return], ByVal billingPlan As Vindicia_OLD.BillingPlan.BillingPlan)
            MyBase.New
            Me.[return] = [return]
            Me.billingPlan = billingPlan
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchByMerchantBillingPlanId", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchByMerchantBillingPlanIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auth As Vindicia_OLD.BillingPlan.Authentication
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public merchantBillingPlanId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal merchantBillingPlanId As String)
            MyBase.New
            Me.auth = auth
            Me.merchantBillingPlanId = merchantBillingPlanId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchByMerchantBillingPlanIdResponse", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchByMerchantBillingPlanIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Vindicia_OLD.BillingPlan.[Return]
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billingPlan As Vindicia_OLD.BillingPlan.BillingPlan
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Vindicia_OLD.BillingPlan.[Return], ByVal billingPlan As Vindicia_OLD.BillingPlan.BillingPlan)
            MyBase.New
            Me.[return] = [return]
            Me.billingPlan = billingPlan
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchByBillingPlanStatus", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchByBillingPlanStatusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auth As Vindicia_OLD.BillingPlan.Authentication
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public status As Vindicia_OLD.BillingPlan.BillingPlanStatus
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal status As Vindicia_OLD.BillingPlan.BillingPlanStatus)
            MyBase.New
            Me.auth = auth
            Me.status = status
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchByBillingPlanStatusResponse", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchByBillingPlanStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Vindicia_OLD.BillingPlan.[Return]
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute("billingPlans", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Vindicia_OLD.BillingPlan.[Return], ByVal billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan)
            MyBase.New
            Me.[return] = [return]
            Me.billingPlans = billingPlans
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchAll", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchAllRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auth As Vindicia_OLD.BillingPlan.Authentication
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public page As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pageSize As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal page As Integer, ByVal pageSize As Integer)
            MyBase.New
            Me.auth = auth
            Me.page = page
            Me.pageSize = pageSize
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchAllResponse", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchAllResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Vindicia_OLD.BillingPlan.[Return]
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute("billingPlans", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Vindicia_OLD.BillingPlan.[Return], ByVal billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan)
            MyBase.New
            Me.[return] = [return]
            Me.billingPlans = billingPlans
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchByMerchantEntitlementId", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchByMerchantEntitlementIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auth As Vindicia_OLD.BillingPlan.Authentication
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public merchantEntitlementId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal merchantEntitlementId As String)
            MyBase.New
            Me.auth = auth
            Me.merchantEntitlementId = merchantEntitlementId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchByMerchantEntitlementIdResponse", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchByMerchantEntitlementIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Vindicia_OLD.BillingPlan.[Return]
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute("billingPlans", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Vindicia_OLD.BillingPlan.[Return], ByVal billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan)
            MyBase.New
            Me.[return] = [return]
            Me.billingPlans = billingPlans
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchAllInSeason", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchAllInSeasonRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auth As Vindicia_OLD.BillingPlan.Authentication
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public page As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pageSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>  _
        Public nowDate As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal page As Integer, ByVal pageSize As Integer, ByVal nowDate As Date)
            MyBase.New
            Me.auth = auth
            Me.page = page
            Me.pageSize = pageSize
            Me.nowDate = nowDate
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchAllInSeasonResponse", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchAllInSeasonResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Vindicia_OLD.BillingPlan.[Return]
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute("billingPlans", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Vindicia_OLD.BillingPlan.[Return], ByVal billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan)
            MyBase.New
            Me.[return] = [return]
            Me.billingPlans = billingPlans
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchAllOffSeason", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchAllOffSeasonRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public auth As Vindicia_OLD.BillingPlan.Authentication
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public page As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public pageSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>  _
        Public nowDate As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal page As Integer, ByVal pageSize As Integer, ByVal nowDate As Date)
            MyBase.New
            Me.auth = auth
            Me.page = page
            Me.pageSize = pageSize
            Me.nowDate = nowDate
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fetchAllOffSeasonResponse", WrapperNamespace:="http://soap.vindicia.com/v7_0/BillingPlan", IsWrapped:=true)>  _
    Partial Public Class fetchAllOffSeasonResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Vindicia_OLD.BillingPlan.[Return]
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://soap.vindicia.com/v7_0/BillingPlan", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute("billingPlans", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Vindicia_OLD.BillingPlan.[Return], ByVal billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan)
            MyBase.New
            Me.[return] = [return]
            Me.billingPlans = billingPlans
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface BillingPlanPortTypeChannel
        Inherits Vindicia_OLD.BillingPlan.BillingPlanPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BillingPlanPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of Vindicia_OLD.BillingPlan.BillingPlanPortType)
        Implements Vindicia_OLD.BillingPlan.BillingPlanPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vindicia_OLD_BillingPlan_BillingPlanPortType_update(ByVal request As Vindicia_OLD.BillingPlan.updateRequest) As Vindicia_OLD.BillingPlan.updateResponse Implements Vindicia_OLD.BillingPlan.BillingPlanPortType.update
            Return MyBase.Channel.update(request)
        End Function
        
        Public Function update(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByRef billingPlan As Vindicia_OLD.BillingPlan.BillingPlan, <System.Runtime.InteropServices.OutAttribute()> ByRef created As Boolean) As Vindicia_OLD.BillingPlan.[Return]
            Dim inValue As Vindicia_OLD.BillingPlan.updateRequest = New Vindicia_OLD.BillingPlan.updateRequest()
            inValue.auth = auth
            inValue.billingPlan = billingPlan
            Dim retVal As Vindicia_OLD.BillingPlan.updateResponse = CType(Me,Vindicia_OLD.BillingPlan.BillingPlanPortType).update(inValue)
            billingPlan = retVal.billingPlan
            created = retVal.created
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vindicia_OLD_BillingPlan_BillingPlanPortType_fetchByVid(ByVal request As Vindicia_OLD.BillingPlan.fetchByVidRequest) As Vindicia_OLD.BillingPlan.fetchByVidResponse Implements Vindicia_OLD.BillingPlan.BillingPlanPortType.fetchByVid
            Return MyBase.Channel.fetchByVid(request)
        End Function
        
        Public Function fetchByVid(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal vid As String, <System.Runtime.InteropServices.OutAttribute()> ByRef billingPlan As Vindicia_OLD.BillingPlan.BillingPlan) As Vindicia_OLD.BillingPlan.[Return]
            Dim inValue As Vindicia_OLD.BillingPlan.fetchByVidRequest = New Vindicia_OLD.BillingPlan.fetchByVidRequest()
            inValue.auth = auth
            inValue.vid = vid
            Dim retVal As Vindicia_OLD.BillingPlan.fetchByVidResponse = CType(Me,Vindicia_OLD.BillingPlan.BillingPlanPortType).fetchByVid(inValue)
            billingPlan = retVal.billingPlan
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vindicia_OLD_BillingPlan_BillingPlanPortType_fetchByMerchantBillingPlanId(ByVal request As Vindicia_OLD.BillingPlan.fetchByMerchantBillingPlanIdRequest) As Vindicia_OLD.BillingPlan.fetchByMerchantBillingPlanIdResponse Implements Vindicia_OLD.BillingPlan.BillingPlanPortType.fetchByMerchantBillingPlanId
            Return MyBase.Channel.fetchByMerchantBillingPlanId(request)
        End Function
        
        Public Function fetchByMerchantBillingPlanId(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal merchantBillingPlanId As String, <System.Runtime.InteropServices.OutAttribute()> ByRef billingPlan As Vindicia_OLD.BillingPlan.BillingPlan) As Vindicia_OLD.BillingPlan.[Return]
            Dim inValue As Vindicia_OLD.BillingPlan.fetchByMerchantBillingPlanIdRequest = New Vindicia_OLD.BillingPlan.fetchByMerchantBillingPlanIdRequest()
            inValue.auth = auth
            inValue.merchantBillingPlanId = merchantBillingPlanId
            Dim retVal As Vindicia_OLD.BillingPlan.fetchByMerchantBillingPlanIdResponse = CType(Me,Vindicia_OLD.BillingPlan.BillingPlanPortType).fetchByMerchantBillingPlanId(inValue)
            billingPlan = retVal.billingPlan
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vindicia_OLD_BillingPlan_BillingPlanPortType_fetchByBillingPlanStatus(ByVal request As Vindicia_OLD.BillingPlan.fetchByBillingPlanStatusRequest) As Vindicia_OLD.BillingPlan.fetchByBillingPlanStatusResponse Implements Vindicia_OLD.BillingPlan.BillingPlanPortType.fetchByBillingPlanStatus
            Return MyBase.Channel.fetchByBillingPlanStatus(request)
        End Function
        
        Public Function fetchByBillingPlanStatus(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal status As Vindicia_OLD.BillingPlan.BillingPlanStatus, <System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan) As Vindicia_OLD.BillingPlan.[Return]
            Dim inValue As Vindicia_OLD.BillingPlan.fetchByBillingPlanStatusRequest = New Vindicia_OLD.BillingPlan.fetchByBillingPlanStatusRequest()
            inValue.auth = auth
            inValue.status = status
            Dim retVal As Vindicia_OLD.BillingPlan.fetchByBillingPlanStatusResponse = CType(Me,Vindicia_OLD.BillingPlan.BillingPlanPortType).fetchByBillingPlanStatus(inValue)
            billingPlans = retVal.billingPlans
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vindicia_OLD_BillingPlan_BillingPlanPortType_fetchAll(ByVal request As Vindicia_OLD.BillingPlan.fetchAllRequest) As Vindicia_OLD.BillingPlan.fetchAllResponse Implements Vindicia_OLD.BillingPlan.BillingPlanPortType.fetchAll
            Return MyBase.Channel.fetchAll(request)
        End Function
        
        Public Function fetchAll(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal page As Integer, ByVal pageSize As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan) As Vindicia_OLD.BillingPlan.[Return]
            Dim inValue As Vindicia_OLD.BillingPlan.fetchAllRequest = New Vindicia_OLD.BillingPlan.fetchAllRequest()
            inValue.auth = auth
            inValue.page = page
            inValue.pageSize = pageSize
            Dim retVal As Vindicia_OLD.BillingPlan.fetchAllResponse = CType(Me,Vindicia_OLD.BillingPlan.BillingPlanPortType).fetchAll(inValue)
            billingPlans = retVal.billingPlans
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vindicia_OLD_BillingPlan_BillingPlanPortType_fetchByMerchantEntitlementId(ByVal request As Vindicia_OLD.BillingPlan.fetchByMerchantEntitlementIdRequest) As Vindicia_OLD.BillingPlan.fetchByMerchantEntitlementIdResponse Implements Vindicia_OLD.BillingPlan.BillingPlanPortType.fetchByMerchantEntitlementId
            Return MyBase.Channel.fetchByMerchantEntitlementId(request)
        End Function
        
        Public Function fetchByMerchantEntitlementId(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal merchantEntitlementId As String, <System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan) As Vindicia_OLD.BillingPlan.[Return]
            Dim inValue As Vindicia_OLD.BillingPlan.fetchByMerchantEntitlementIdRequest = New Vindicia_OLD.BillingPlan.fetchByMerchantEntitlementIdRequest()
            inValue.auth = auth
            inValue.merchantEntitlementId = merchantEntitlementId
            Dim retVal As Vindicia_OLD.BillingPlan.fetchByMerchantEntitlementIdResponse = CType(Me,Vindicia_OLD.BillingPlan.BillingPlanPortType).fetchByMerchantEntitlementId(inValue)
            billingPlans = retVal.billingPlans
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vindicia_OLD_BillingPlan_BillingPlanPortType_fetchAllInSeason(ByVal request As Vindicia_OLD.BillingPlan.fetchAllInSeasonRequest) As Vindicia_OLD.BillingPlan.fetchAllInSeasonResponse Implements Vindicia_OLD.BillingPlan.BillingPlanPortType.fetchAllInSeason
            Return MyBase.Channel.fetchAllInSeason(request)
        End Function
        
        Public Function fetchAllInSeason(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal page As Integer, ByVal pageSize As Integer, ByVal nowDate As Date, <System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan) As Vindicia_OLD.BillingPlan.[Return]
            Dim inValue As Vindicia_OLD.BillingPlan.fetchAllInSeasonRequest = New Vindicia_OLD.BillingPlan.fetchAllInSeasonRequest()
            inValue.auth = auth
            inValue.page = page
            inValue.pageSize = pageSize
            inValue.nowDate = nowDate
            Dim retVal As Vindicia_OLD.BillingPlan.fetchAllInSeasonResponse = CType(Me,Vindicia_OLD.BillingPlan.BillingPlanPortType).fetchAllInSeason(inValue)
            billingPlans = retVal.billingPlans
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Vindicia_OLD_BillingPlan_BillingPlanPortType_fetchAllOffSeason(ByVal request As Vindicia_OLD.BillingPlan.fetchAllOffSeasonRequest) As Vindicia_OLD.BillingPlan.fetchAllOffSeasonResponse Implements Vindicia_OLD.BillingPlan.BillingPlanPortType.fetchAllOffSeason
            Return MyBase.Channel.fetchAllOffSeason(request)
        End Function
        
        Public Function fetchAllOffSeason(ByVal auth As Vindicia_OLD.BillingPlan.Authentication, ByVal page As Integer, ByVal pageSize As Integer, ByVal nowDate As Date, <System.Runtime.InteropServices.OutAttribute()> ByRef billingPlans() As Vindicia_OLD.BillingPlan.BillingPlan) As Vindicia_OLD.BillingPlan.[Return]
            Dim inValue As Vindicia_OLD.BillingPlan.fetchAllOffSeasonRequest = New Vindicia_OLD.BillingPlan.fetchAllOffSeasonRequest()
            inValue.auth = auth
            inValue.page = page
            inValue.pageSize = pageSize
            inValue.nowDate = nowDate
            Dim retVal As Vindicia_OLD.BillingPlan.fetchAllOffSeasonResponse = CType(Me,Vindicia_OLD.BillingPlan.BillingPlanPortType).fetchAllOffSeason(inValue)
            billingPlans = retVal.billingPlans
            Return retVal.[return]
        End Function
    End Class
End Namespace
