'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Vindicia.Account
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://soap.vindicia.com/Account", ConfigurationName:="Vindicia.Account.AccountPortType")>  _
    Public Interface AccountPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Account#update", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.AutoBill)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair))> _
        Function update(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef account As Vindicia.AllDataTypes.Account, <System.Runtime.InteropServices.OutAttribute()> ByRef created As Boolean) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Account#stopAutoBilling", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.AutoBill)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair))> _
        Function stopAutoBilling(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef account As Vindicia.AllDataTypes.Account, ByVal autobills() As AllDataTypes.AutoBill, ByVal disentitle As Boolean, ByVal force As Boolean) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Account#updatePaymentMethod", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.AutoBill)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair))> _
        Function updatePaymentMethod(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef account As Vindicia.AllDataTypes.Account, <System.Runtime.InteropServices.OutAttribute()> ByRef validated As Boolean, ByVal paymentMethod As Vindicia.AllDataTypes.PaymentMethod, ByVal replaceOnAllAutoBills As Boolean, ByVal updateBehavior As Vindicia.AllDataTypes.PaymentUpdateBehavior, ByVal numCycles As Integer) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Account#fetchByMerchantAccountId", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.AutoBill)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair))> _
        Function fetchByMerchantAccountId(<System.Runtime.InteropServices.OutAttribute()> ByRef account As Vindicia.AllDataTypes.Account, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantAccountId As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Account#fetchByVid", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.AutoBill)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair))> _
        Function fetchByVid(<System.Runtime.InteropServices.OutAttribute()> ByRef account As Vindicia.AllDataTypes.Account, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal vid As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Account#fetchByEmail", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.AutoBill)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair))> _
        Function fetchByEmail(<System.Runtime.InteropServices.OutAttribute()> ByRef accounts() As AllDataTypes.Account, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal emailAddress As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
    End Interface

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface AccountPortTypeChannel
        Inherits Vindicia.Account.AccountPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class AccountPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of Vindicia.Account.AccountPortType)
        Implements Vindicia.Account.AccountPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function update(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef account As Vindicia.AllDataTypes.Account, <System.Runtime.InteropServices.OutAttribute()> ByRef created As Boolean) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Account.AccountPortType.update
            Return MyBase.Channel.update(auth, account, created)
        End Function
        
        Public Function stopAutoBilling(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef account As Vindicia.AllDataTypes.Account, ByVal autobills() As AllDataTypes.AutoBill, ByVal disentitle As Boolean, ByVal force As Boolean) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Account.AccountPortType.stopAutoBilling
            Return MyBase.Channel.stopAutoBilling(auth, account, autobills, disentitle, force)
        End Function
        
        Public Function updatePaymentMethod(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef account As Vindicia.AllDataTypes.Account, <System.Runtime.InteropServices.OutAttribute()> ByRef validated As Boolean, ByVal paymentMethod As Vindicia.AllDataTypes.PaymentMethod, ByVal replaceOnAllAutoBills As Boolean, ByVal updateBehavior As Vindicia.AllDataTypes.PaymentUpdateBehavior, ByVal numCycles As Integer) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Account.AccountPortType.updatePaymentMethod
            Return MyBase.Channel.updatePaymentMethod(auth, account, validated, paymentMethod, replaceOnAllAutoBills, updateBehavior, numCycles)
        End Function
        
        Public Function fetchByMerchantAccountId(<System.Runtime.InteropServices.OutAttribute()> ByRef account As Vindicia.AllDataTypes.Account, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantAccountId As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Account.AccountPortType.fetchByMerchantAccountId
            Return MyBase.Channel.fetchByMerchantAccountId(account, auth, merchantAccountId)
        End Function
        
        Public Function fetchByVid(<System.Runtime.InteropServices.OutAttribute()> ByRef account As Vindicia.AllDataTypes.Account, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal vid As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Account.AccountPortType.fetchByVid
            Return MyBase.Channel.fetchByVid(account, auth, vid)
        End Function
        
        Public Function fetchByEmail(<System.Runtime.InteropServices.OutAttribute()> ByRef accounts() As AllDataTypes.Account, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal emailAddress As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Account.AccountPortType.fetchByEmail
            Return MyBase.Channel.fetchByEmail(accounts, auth, emailAddress)
        End Function
    End Class
End Namespace
