'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Vindicia.Product
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://soap.vindicia.com/Product", ConfigurationName:="Vindicia.Product.ProductPortType")>  _
    Public Interface ProductPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Product#update", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.PaymentMethod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Vindicia.AllDataTypes.BillingPlanPeriod))> _
        Function update(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef product As Vindicia.AllDataTypes.Product, <System.Runtime.InteropServices.OutAttribute()> ByRef created As Boolean, ByVal duplicateBehavior As Vindicia.AllDataTypes.DuplicateBehavior) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Product#fetchByVid", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.PaymentMethod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function fetchByVid(<System.Runtime.InteropServices.OutAttribute()> ByRef product As Vindicia.AllDataTypes.Product, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal vid As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Product#fetchByMerchantProductId", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.PaymentMethod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function fetchByMerchantProductId(<System.Runtime.InteropServices.OutAttribute()> ByRef product As Vindicia.AllDataTypes.Product, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantProductId As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Product#fetchByAccount", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.PaymentMethod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function fetchByAccount(<System.Runtime.InteropServices.OutAttribute()> ByRef products() As Vindicia.AllDataTypes.Product, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal account As Vindicia.AllDataTypes.Account) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Product#fetchAll", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.PaymentMethod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function fetchAll(<System.Runtime.InteropServices.OutAttribute()> ByRef products() As Vindicia.AllDataTypes.Product, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal page As Integer, ByVal pageSize As Integer) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://soap.vindicia.com/Product#fetchByMerchantEntitlementId", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, Use:=System.ServiceModel.OperationFormatUse.Encoded), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.TaxExemption)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.PaymentMethod)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.MerchantEntitlementId)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.NameValuePair)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPrice)), _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(AllDataTypes.BillingPlanPeriod))> _
        Function fetchByMerchantEntitlementId(<System.Runtime.InteropServices.OutAttribute()> ByRef products() As Vindicia.AllDataTypes.Product, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantEntitlementId As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Vindicia.AllDataTypes.[Return]
    End Interface

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ProductPortTypeChannel
        Inherits Vindicia.Product.ProductPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ProductPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of Vindicia.Product.ProductPortType)
        Implements Vindicia.Product.ProductPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function update(ByVal auth As Vindicia.AllDataTypes.Authentication, ByRef product As Vindicia.AllDataTypes.Product, <System.Runtime.InteropServices.OutAttribute()> ByRef created As Boolean, ByVal duplicateBehavior As Vindicia.AllDataTypes.DuplicateBehavior) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Product.ProductPortType.update
            Return MyBase.Channel.update(auth, product, created, duplicateBehavior)
        End Function
        
        Public Function fetchByVid(<System.Runtime.InteropServices.OutAttribute()> ByRef product As Vindicia.AllDataTypes.Product, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal vid As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Product.ProductPortType.fetchByVid
            Return MyBase.Channel.fetchByVid(product, auth, vid)
        End Function
        
        Public Function fetchByMerchantProductId(<System.Runtime.InteropServices.OutAttribute()> ByRef product As Vindicia.AllDataTypes.Product, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantProductId As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Product.ProductPortType.fetchByMerchantProductId
            Return MyBase.Channel.fetchByMerchantProductId(product, auth, merchantProductId)
        End Function
        
        Public Function fetchByAccount(<System.Runtime.InteropServices.OutAttribute()> ByRef products() As Vindicia.AllDataTypes.Product, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal account As Vindicia.AllDataTypes.Account) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Product.ProductPortType.fetchByAccount
            Return MyBase.Channel.fetchByAccount(products, auth, account)
        End Function
        
        Public Function fetchAll(<System.Runtime.InteropServices.OutAttribute()> ByRef products() As Vindicia.AllDataTypes.Product, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal page As Integer, ByVal pageSize As Integer) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Product.ProductPortType.fetchAll
            Return MyBase.Channel.fetchAll(products, auth, page, pageSize)
        End Function
        
        Public Function fetchByMerchantEntitlementId(<System.Runtime.InteropServices.OutAttribute()> ByRef products() As Vindicia.AllDataTypes.Product, ByVal auth As Vindicia.AllDataTypes.Authentication, ByVal merchantEntitlementId As String) As Vindicia.AllDataTypes.[Return] Implements Vindicia.Product.ProductPortType.fetchByMerchantEntitlementId
            Return MyBase.Channel.fetchByMerchantEntitlementId(products, auth, merchantEntitlementId)
        End Function
    End Class
End Namespace
