drop procedure sp_GetRecentlyViewedItems
drop procedure sp_MailingRemoveDuplicates
drop procedure sp_StoreDepartmentDelete
drop procedure sp_StoreDepartmentInsert
drop procedure sp_StoreDepartmentMove
drop procedure sp_StoreDepartmentRename
drop procedure sp_GetAttributeTree
drop procedure sp_GetTemplateAttributeTree
drop procedure sp_GetTemplateAttributeTreeByTemplate
drop procedure sp_ValidateSKU
drop function fn_SearchBuildSKU
drop view StoreSalesView

drop table GiftMessage
drop table AdminAccess
drop table AdminAdminGroup	
drop table AdminGroup	
drop table AdminLog	
drop table AdminPassword	
drop table AdminSection	
drop table Admin	
drop table BannerBannerGroup	
drop table BannerGroup	
drop table BannerOrderTracking	
drop table BannerTracking	
drop table Banner	
drop table ContentToolContent
drop table ContentToolRegionModule	
drop table ContentToolPageRegion	
drop table ContentToolModule	
drop table ContentToolPage	
drop table ContentToolNavigation	
drop table ContentToolSection	
drop table ContentToolTemplateRegion	
drop table ContentToolTemplate	
drop table Country	
drop table Log4net	
drop table Mailing_Lyris_Member	
drop table Mailing_Lyris_Outmail	
drop table MailingGroupList	
drop table MailingGroup	
drop table MailingLinkHit	
drop table MailingLink	
drop table MailingListMember	
drop table MailingMessageOpen	
drop table MailingMessageSlot	
drop table MailingRecipient	
drop table MailingMember	
drop table MailingTemplateSlot	
drop table MailingTemplate	
drop table MailingMessage	
drop table MailingList	
drop table MemberReminderLog	
drop table MemberReminder	
drop table MemberWishlistItemAttribute	
drop table MemberWishlistItem	
drop table PaymentLog	
drop table Referral	
drop table ReferralClick	
drop table SearchTerm	
drop table State	
drop table CustomText	
drop table StoreDepartmentItem	
drop table StoreFeature	
drop table StoreOrderNote	
drop table StoreOrderStatus	
drop table StoreOrderItemAttribute	
drop table StoreOrderItem	
drop table StoreOrderRecipient	
drop table StoreOrder	
drop table StoreItemAttributeTempGuid	
drop table StoreItemAttributeTemp	
drop table StoreItemAttribute	
drop table StoreItemFeature	
drop table StoreItemImage	
drop table StoreItemTemplateAttribute	
drop table StoreItemTemplate	
drop table StorePromotionItem	
drop table StorePromotion	
drop table StoreRecentlyViewed	
drop table StoreRelatedItem	
drop table StoreSequence	
drop table StoreShippingMethod	
drop table StoreShippingRange	
drop table StoreItem	
drop table Sysparam	
drop table CreditCardType	
drop table HowHeard	
drop table LookupSwatch
drop table MemberAddress
drop table Member	
drop table StoreBrand	
drop table StoreDepartment	
